# Favicon
favicon: /favicon.ico

# SEO
keywords: 生活,博客,后端,游戏

# Site title separator
separator: '-'

# RSS
rss: /atom.xml

# SNS config
sns:
  Blog: /archives
  GitHub: https://github.com/zgshen

# Nav menu
menu:
  Home: /
  #Archives: /archives
  About: /about
  Search: https://www.google.com/search?q=site:zguishen.com/